services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile                                                                
    restart: always

  reverse-proxy:
    build: 
      context: /reverse-proxy
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    restart: always
